### ISSUE TITLE
Unable to connect to Cassandra

### ISSUE THREAD

**Issue by daveroberts** [killrweather/killrweather#24]
I'm trying to run the demo.  After importing the data into Cassandra I try to run with sbt app/run.  Instead of being presented with three choices on which to run, I am given an error.  Some lines omitted:

```bash
vagrant@vagrant-ubuntu-trusty-64:~/killrweather$ sbt app/run
[info] Loading project definition from /home/vagrant/killrweather/project
[warn] There may be incompatibilities among your library dependencies.
[warn] Here are some of the libraries that were evicted:
[warn] 	* com.typesafe.sbt:sbt-git:0.6.2 -> 0.6.4
[warn] Run 'evicted' to see detailed eviction warnings
[info] Set current project to KillrWeather (in build file:/home/vagrant/killrweather/)
[info] Running com.datastax.killrweather.KillrWeatherApp 
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/vagrant/.ivy2/cache/ch.qos.logback/logback-classic/jars/logback-classic-1.0.13.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/vagrant/.ivy2/cache/org.slf4j/slf4j-log4j12/jars/slf4j-log4j12-1.6.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
[INFO] [2015-09-16 15:00:59,279] [akka.event.slf4j.Slf4jLogger]: Slf4jLogger started
[INFO] [2015-09-16 15:00:59,676] [Remoting]: Starting remoting
[INFO] [2015-09-16 15:01:00,019] [Remoting]: Remoting started; listening on addresses :[akka.tcp://KillrWeather@127.0.0.1:2550]
[INFO] [2015-09-16 15:01:00,042] [Cluster(akka://KillrWeather)]: Cluster Node [akka.tcp://KillrWeather@127.0.0.1:2550] - Starting up...
[INFO] [2015-09-16 15:01:00,161] [Cluster(akka://KillrWeather)]: Cluster Node [akka.tcp://KillrWeather@127.0.0.1:2550] - Registered cluster JMX MBean [akka:type=Cluster]
[INFO] [2015-09-16 15:01:00,162] [Cluster(akka://KillrWeather)]: Cluster Node [akka.tcp://KillrWeather@127.0.0.1:2550] - Started up successfully
[INFO] [2015-09-16 15:01:00,189] [Cluster(akka://KillrWeather)]: Cluster Node [akka.tcp://KillrWeather@127.0.0.1:2550] - No seed-nodes configured, manual cluster join required
[INFO] [2015-09-16 15:01:00,674] [Cluster(akka://KillrWeather)]: Cluster Node [akka.tcp://KillrWeather@127.0.0.1:2550] - Metrics collection has started successfully
ZooKeeperServer isRunning: true
log4j:WARN No appenders could be found for logger (kafka.utils.VerifiableProperties).
log4j:WARN Please initialize the log4j system properly.
Starting the Kafka server at 10.0.2.15:2181
[INFO] [2015-09-16 15:01:07,192] [akka.event.slf4j.Slf4jLogger]: Slf4jLogger started
[INFO] [2015-09-16 15:01:07,220] [Remoting]: Starting remoting
[INFO] [2015-09-16 15:01:07,235] [Remoting]: Remoting started; listening on addresses :[akka.tcp://sparkDriver@vagrant-ubuntu-trusty-64:36445]
[INFO] [2015-09-16 15:01:07,667] [org.spark-project.jetty.server.Server]: jetty-8.y.z-SNAPSHOT
[INFO] [2015-09-16 15:01:07,719] [org.spark-project.jetty.server.AbstractConnector]: Started SocketConnector@0.0.0.0:36072
[INFO] [2015-09-16 15:01:08,041] [org.spark-project.jetty.server.Server]: jetty-8.y.z-SNAPSHOT
[INFO] [2015-09-16 15:01:08,080] [org.spark-project.jetty.server.AbstractConnector]: Started SelectChannelConnector@0.0.0.0:4040
[INFO] [2015-09-16 15:01:09,078] [Cluster(akka://KillrWeather)]: Cluster Node [akka.tcp://KillrWeather@127.0.0.1:2550] - Node [akka.tcp://KillrWeather@127.0.0.1:2550] is JOINING, roles [analytics]
[INFO] [2015-09-16 15:01:09,099] [com.datastax.killrweather.NodeGuardian]: Starting at akka.tcp://KillrWeather@127.0.0.1:2550
[INFO] [2015-09-16 15:01:09,100] [Cluster(akka://KillrWeather)]: Cluster Node [akka.tcp://KillrWeather@127.0.0.1:2550] - Trying to join seed nodes [akka.tcp://KillrWeather@127.0.0.1:2550] when already part of a cluster, ignoring
[INFO] [2015-09-16 15:01:09,197] [Cluster(akka://KillrWeather)]: Cluster Node [akka.tcp://KillrWeather@127.0.0.1:2550] - Leader is moving node [akka.tcp://KillrWeather@127.0.0.1:2550] to [Up]
[DEBUG] [2015-09-16 15:01:09,203] [com.datastax.killrweather.NodeGuardian]: Member [akka.tcp://KillrWeather@127.0.0.1:2550] joined cluster.
[ERROR] [2015-09-16 15:01:11,059] [akka.actor.OneForOneStrategy]: Failed to open native connection to Cassandra at {10.0.2.15}:9042
akka.actor.ActorInitializationException: exception during creation
```

**Comment by helena** [comment]
Hi @daveroberts - first, running 

     sbt app/run

will only show you the killrweather 'app' runnable, noted here https://github.com/killrweather/killrweather#from-command-line for step 1.

Once that is running you then proceed down to the other runnable commands to run first the ingestion client, then you can also run the query api client. As noted in the README you only see multiple runnables when running

       sbt clients/run
 
So you are never presented with 3 options to run with sbt app/run, this is documented.

Second, to address your connection with cassandra issue, looking at your logs I am guessing this is a either a) you don't have Cassandra installed locally or b) you simply need to configure the cassandra host IP. I simply set in /etc/hosts the mapping to 127.0.0.1. I'm not sure if you changed the config for it already to look for 10.0.2.15 but it's looking to connect at 10.0.2.15. So you can either set CASSANDRA_SEEDS to your host, picked up here https://github.com/killrweather/killrweather/blob/wip-18-add-killrUi/killrweather-app/src/main/resources/reference.conf#L34 or with either of the properties here for env or -D https://github.com/killrweather/killrweather/blob/wip-18-add-killrUi/killrweather-app/src/main/scala/com/datastax/killrweather/WeatherSettings.scala#L67-L68 or modify your host mapping to 127.0.0.1.

**Comment by daveroberts** [comment]
Thank you for your response.  I'm running this in Virtual Box, and 10.0.2.15 is the NAT IP address of the local system.  Cassandra is installed locally.  I tried adding 10.0.2.15 to $CASSANDRA_HOME/conf/cassandra.yaml as suggested and there was no change.  I also tried adding: 10.0.2.15 localhost to my /etc/hosts file and saw no change in behavior.  Here is the output of ifconfig -a
```bash
vagrant@vagrant-ubuntu-trusty-64:~$ ifconfig -a
eth0      Link encap:Ethernet  HWaddr 08:00:27:c3:24:cc  
          inet addr:10.0.2.15  Bcast:10.0.2.255  Mask:255.255.255.0
          inet6 addr: fe80::a00:27ff:fec3:24cc/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:36354 errors:0 dropped:0 overruns:0 frame:0
          TX packets:17839 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:25512811 (25.5 MB)  TX bytes:1654056 (1.6 MB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:33834 errors:0 dropped:0 overruns:0 frame:0
          TX packets:33834 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:6312033 (6.3 MB)  TX bytes:6312033 (6.3 MB)
```

Any additional help is appreciated.

**Comment by melurie** [comment]
For those who don't want to mess with /etc/hosts (and you probably shouldn't), you can modify the cassandra host IP at load time by doing something like 
~~~
sbt app/run -Dcassandra.connection.host=127.0.0.1
~~~

**Comment by gkericks** [comment]
Hi all,

I am having the exact same issue:

> sbt app/run -Dcassandra.connection.host=127.0.0.1
[info] Loading project definition from /home/graham/StrataTutorials/killrweather/project
[warn] There may be incompatibilities among your library dependencies.
[warn] Here are some of the libraries that were evicted:
[warn] 	* com.typesafe.sbt:sbt-git:0.6.2 -> 0.6.4
[warn] Run 'evicted' to see detailed eviction warnings
[info] Set current project to KillrWeather (in build file:/home/graham/StrataTutorials/killrweather/)
[info] Running com.datastax.killrweather.KillrWeatherApp 
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/root/.ivy2/cache/ch.qos.logback/logback-classic/jars/logback-classic-1.0.13.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/root/.ivy2/cache/org.slf4j/slf4j-log4j12/jars/slf4j-log4j12-1.6.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
[INFO] [2016-03-25 14:13:16,298] [akka.event.slf4j.Slf4jLogger]: Slf4jLogger started
[INFO] [2016-03-25 14:13:16,370] [Remoting]: Starting remoting
[INFO] [2016-03-25 14:13:16,730] [Remoting]: Remoting started; listening on addresses :[akka.tcp://KillrWeather@127.0.0.1:2550]
[INFO] [2016-03-25 14:13:16,742] [Cluster(akka://KillrWeather)]: Cluster Node [akka.tcp://KillrWeather@127.0.0.1:2550] - Starting up...
[INFO] [2016-03-25 14:13:16,812] [Cluster(akka://KillrWeather)]: Cluster Node [akka.tcp://KillrWeather@127.0.0.1:2550] - Registered cluster JMX MBean [akka:type=Cluster]
[INFO] [2016-03-25 14:13:16,812] [Cluster(akka://KillrWeather)]: Cluster Node [akka.tcp://KillrWeather@127.0.0.1:2550] - Started up successfully
[INFO] [2016-03-25 14:13:16,822] [Cluster(akka://KillrWeather)]: Cluster Node [akka.tcp://KillrWeather@127.0.0.1:2550] - No seed-nodes configured, manual cluster join required
[INFO] [2016-03-25 14:13:16,874] [Cluster(akka://KillrWeather)]: Cluster Node [akka.tcp://KillrWeather@127.0.0.1:2550] - Metrics collection has started successfully
ZooKeeperServer isRunning: true
log4j:WARN No appenders could be found for logger (kafka.utils.VerifiableProperties).
log4j:WARN Please initialize the log4j system properly.
Starting the Kafka server at 127.0.1.1:2181
[WARN] [2016-03-25 14:13:23,146] [org.apache.spark.util.Utils]: Your hostname, graham-ThinkPad-Edge-E540 resolves to a loopback address: 127.0.1.1; using 192.168.1.75 instead (on interface wlan0)
[WARN] [2016-03-25 14:13:23,147] [org.apache.spark.util.Utils]: Set SPARK_LOCAL_IP if you need to bind to another address
[INFO] [2016-03-25 14:13:23,344] [akka.event.slf4j.Slf4jLogger]: Slf4jLogger started
[INFO] [2016-03-25 14:13:23,349] [Remoting]: Starting remoting
[INFO] [2016-03-25 14:13:23,357] [Remoting]: Remoting started; listening on addresses :[akka.tcp://sparkDriver@192.168.1.75:44383]
[INFO] [2016-03-25 14:13:23,478] [org.spark-project.jetty.server.Server]: jetty-8.y.z-SNAPSHOT
>[INFO] [2016-03-25 14:13:23,490] [org.spark-project.jetty.server.AbstractConnector]: Started SocketConnector@0.0.0.0:50978
>[INFO] [2016-03-25 14:13:23,589] [org.spark-project.jetty.server.Server]: jetty-8.y.z-SNAPSHOT
>[INFO] [2016-03-25 14:13:23,598] [org.spark-project.jetty.server.AbstractConnector]: Started SelectChannelConnector@0.0.0.0:4040
>[INFO] [2016-03-25 14:13:23,963] [Cluster(akka://KillrWeather)]: Cluster Node [akka.tcp://KillrWeather@127.0.0.1:2550] - Node [akka.tcp://KillrWeather@127.0.0.1:2550] is JOINING, roles [analytics]
>[INFO] [2016-03-25 14:13:23,980] [com.datastax.killrweather.NodeGuardian]: Starting at akka.tcp://KillrWeather@127.0.0.1:2550
>[INFO] [2016-03-25 14:13:23,981] [Cluster(akka://KillrWeather)]: Cluster Node [akka.tcp://KillrWeather@127.0.0.1:2550] - Trying to join seed nodes [akka.tcp://KillrWeather@127.0.0.1:2550] when already part of a cluster, ignoring
>[ERROR] [2016-03-25 14:13:24,622] [akka.actor.OneForOneStrategy]: Failed to open native connection to Cassandra at {127.0.0.1}:9042
>akka.actor.ActorInitializationException: exception during creation
	at akka.actor.ActorInitializationException$.apply(Actor.scala:166) ~[akka-actor_2.10-2.3.11.jar:na]
	at akka.actor.ActorCell.create(ActorCell.scala:596) ~[akka-actor_2.10-2.3.11.jar:na]
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:456) ~[akka-actor_2.10-2.3.11.jar:na]
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478) ~[akka-actor_2.10-2.3.11.jar:na]
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:263) ~[akka-actor_2.10-2.3.11.jar:na]
	at akka.dispatch.Mailbox.run(Mailbox.scala:219) ~[akka-actor_2.10-2.3.11.jar:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [akka-actor_2.10-2.3.11.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.10.5.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.10.5.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.10.5.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.10.5.jar:na]
>Caused by: java.io.IOException: Failed to open native connection to Cassandra at {127.0.0.1}:9042
	at com.datastax.spark.connector.cql.CassandraConnector$.com$datastax$spark$connector$cql$CassandraConnector$$createSession(CassandraConnector.scala:181) ~[spark-cassandra-connector_2.10-1.3.0-M1.jar:1.3.0-M1]
	at com.datastax.spark.connector.cql.CassandraConnector$$anonfun$2.apply(CassandraConnector.scala:167) ~[spark-cassandra-connector_2.10-1.3.0-M1.jar:1.3.0-M1]
	at com.datastax.spark.connector.cql.CassandraConnector$$anonfun$2.apply(CassandraConnector.scala:167) ~[spark-cassandra-connector_2.10-1.3.0-M1.jar:1.3.0-M1]
	at com.datastax.spark.connector.cql.RefCountedCache.createNewValueAndKeys(RefCountedCache.scala:31) ~[spark-cassandra-connector_2.10-1.3.0-M1.jar:1.3.0-M1]
	at com.datastax.spark.connector.cql.RefCountedCache.acquire(RefCountedCache.scala:56) ~[spark-cassandra-connector_2.10-1.3.0-M1.jar:1.3.0-M1]
	at com.datastax.spark.connector.cql.CassandraConnector.openSession(CassandraConnector.scala:76) ~[spark-cassandra-connector_2.10-1.3.0-M1.jar:1.3.0-M1]
	at com.datastax.spark.connector.cql.CassandraConnector.withSessionDo(CassandraConnector.scala:104) ~[spark-cassandra-connector_2.10-1.3.0-M1.jar:1.3.0-M1]
	at com.datastax.spark.connector.cql.CassandraConnector.withClusterDo(CassandraConnector.scala:115) ~[spark-cassandra-connector_2.10-1.3.0-M1.jar:1.3.0-M1]
	at com.datastax.spark.connector.cql.Schema$.fromCassandra(Schema.scala:243) ~[spark-cassandra-connector_2.10-1.3.0-M1.jar:1.3.0-M1]
	at com.datastax.spark.connector.writer.TableWriter$.apply(TableWriter.scala:182) ~[spark-cassandra-connector_2.10-1.3.0-M1.jar:1.3.0-M1]
	at com.datastax.spark.connector.streaming.DStreamFunctions.saveToCassandra(DStreamFunctions.scala:32) ~[spark-cassandra-connector_2.10-1.3.0-M1.jar:1.3.0-M1]
	at com.datastax.killrweather.KafkaStreamingActor.<init>(KafkaStreamingActor.scala:45) ~[classes/:na]
	at com.datastax.killrweather.NodeGuardian$$anonfun$1.apply(NodeGuardian.scala:42) ~[classes/:na]
	at com.datastax.killrweather.NodeGuardian$$anonfun$1.apply(NodeGuardian.scala:42) ~[classes/:na]
	at akka.actor.TypedCreatorFunctionConsumer.produce(Props.scala:343) ~[akka-actor_2.10-2.3.11.jar:na]
	at akka.actor.Props.newActor(Props.scala:252) ~[akka-actor_2.10-2.3.11.jar:na]
	at akka.actor.ActorCell.newActor(ActorCell.scala:552) ~[akka-actor_2.10-2.3.11.jar:na]
	at akka.actor.ActorCell.create(ActorCell.scala:578) ~[akka-actor_2.10-2.3.11.jar:na]
	... 9 common frames omitted
>Caused by: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /127.0.0.1:9042 (com.datastax.driver.core.exceptions.InvalidQueryException: unconfigured table schema_keyspaces))
	at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:223) ~[cassandra-driver-core-2.1.5.jar:na]
	at com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:78) ~[cassandra-driver-core-2.1.5.jar:na]
	at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1230) ~[cassandra-driver-core-2.1.5.jar:na]
	at com.datastax.driver.core.Cluster.getMetadata(Cluster.java:333) ~[cassandra-driver-core-2.1.5.jar:na]
	at com.datastax.spark.connector.cql.CassandraConnector$.com$datastax$spark$connector$cql$CassandraConnector$$createSession(CassandraConnector.scala:174) ~[spark-cassandra-connector_2.10-1.3.0-M1.jar:1.3.0-M1]
	... 26 common frames omitted
[INFO] [2016-03-25 14:13:24,839] [Cluster(akka://KillrWeather)]: Cluster Node [akka.tcp://KillrWeather@127.0.0.1:2550] - Leader is moving node [akka.tcp://KillrWeather@127.0.0.1:2550] to [Up]
>[DEBUG] [2016-03-25 14:13:24,842] [com.datastax.killrweather.NodeGuardian]: Member [akka.tcp://KillrWeather@127.0.0.1:2550] joined cluster.
>[DEBUG] [2016-03-25 14:13:27,418] [com.datastax.killrweather.NodeGuardian]: NodeMetrics[heap-memory-max:1006108672,system-load-average:2.38,heap-memory-committed:1006108672,heap-memory-used:232581448,cpu-combined:0.012531328320802004]
>[DEBUG] [2016-03-25 14:13:36,887] [com.datastax.killrweather.NodeGuardian]: NodeMetrics[cpu-combined:0.01485017236807213,heap-memory-max:1006108672,heap-memory-committed:1006108672,heap-memory-used:236025032,system-load-average:2.01]


I can connect to my Cassandra instance via `cqlsh` which verifies that it is running on 127.0.0.1.  


> Connected to Test Cluster at 127.0.0.1:9042.
> [cqlsh 5.0.1 | Cassandra 3.4 | CQL spec 3.4.0 | Native protocol v4]
> Use HELP for help.
> cqlsh

I have a hunch that this has to do with the evicted warning that both me and @daveroberts are seeing. I followed the procure in the `killrweather` readme exactly. This is using 0.13 of sbt and apache-cassandra 3.4.

**Comment by jmacias** [comment]
Have the same issue, I am running Cassandra 3.4. After updating the dependencies 

  val CassandraDriver = "3.0.0"

and 

  val SparkCassandra = "1.5.0"

I was able to start the application

**Comment by qyc5937** [comment]
Have the same issue with cassandra 3.7.0 and no luck.  Ended up starting a new installation with cassandra 2.1.5.  That and sbt app/run -Dcassandra.connection.host=127.0.0.1 flag seems to work.

**Comment by SinghSeema** [comment]
Having the same issue . Changing version as  said above  and with sbt app/run -Dcassandra.connection.host=127.0.0.1 it did work for me getting same connection issue . Any suggestions?


Cassandra version I am using is -
cqlsh> show VERSION
**[cqlsh 5.0.1 | Cassandra 3.9.0 | CQL spec 3.4.2 | Native protocol v4]**
cqlsh>



Changed version:
  val Cassandra      = "3.9.0"//"2.1.3"
  val CassandraDriver = "3.0.0"//"2.1.5"

  val Spark          = "1.6.0"//"1.3.1"
  val SparkCassandra = "1.6.0"//"1.3.0-M1"



log snippet ********************************************
[DEBUG] [2016-11-17 14:02:58,437] [com.datastax.killrweather.NodeGuardian]: Node
Metrics[heap-memory-used:106061144,heap-memory-max:477102080,cpu-combined:0.0470
4704704704705,heap-memory-committed:315621376]
[ERROR] [2016-11-17 14:03:13,000] [akka.actor.OneForOneStrategy]: Failed to open
 native connection to Cassandra at {169.254.121.97}:9042
akka.actor.ActorInitializationException: exception during creation
        at akka.actor.ActorInitializationException$.apply(Actor.scala:166) ~[akk
a-actor_2.10-2.3.11.jar:na]
        at akka.actor.ActorCell.create(ActorCell.scala:596) ~[akka-actor_2.10-2.
3.11.jar:na]

**Comment by hsnusonic** [comment]
Thanks @stoyanr
I followed his revision and it seems to work.
