### ISSUE TITLE
ZooKeeper fail to start

### ISSUE THREAD

**Issue by dipietro-salvatore** [killrweather/killrweather#28]
Hi,
I am trying to start the application but seems to me that Zookeeper failed to start. 
Below the log. How can I fix this?

Thank you

root@debian:~/git/killrweather# sbt app/run
[info] Loading project definition from /root/git/killrweather/project
[warn] There may be incompatibilities among your library dependencies.
[warn] Here are some of the libraries that were evicted:
[warn]  * com.typesafe.sbt:sbt-git:0.6.2 -> 0.6.4
[warn] Run 'evicted' to see detailed eviction warnings
[info] Set current project to KillrWeather (in build file:/root/git/killrweather/)
[info] Running com.datastax.killrweather.KillrWeatherApp 
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/root/.ivy2/cache/ch.qos.logback/logback-classic/jars/logback-classic-1.0.13.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/root/.ivy2/cache/org.slf4j/slf4j-log4j12/jars/slf4j-log4j12-1.6.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
[INFO] [2015-12-15 16:40:52,251] [akka.event.slf4j.Slf4jLogger]: Slf4jLogger started
[INFO] [2015-12-15 16:40:52,435] [Remoting]: Starting remoting
[INFO] [2015-12-15 16:40:53,215] [Remoting]: Remoting started; listening on addresses :[akka.tcp://KillrWeather@127.0.0.1:2550]
[INFO] [2015-12-15 16:40:53,255] [Cluster(akka://KillrWeather)]: Cluster Node [akka.tcp://KillrWeather@127.0.0.1:2550] - Starting up...
[INFO] [2015-12-15 16:40:53,476] [Cluster(akka://KillrWeather)]: Cluster Node [akka.tcp://KillrWeather@127.0.0.1:2550] - Registered cluster JMX MBean [akka:type=Cluster]
[INFO] [2015-12-15 16:40:53,478] [Cluster(akka://KillrWeather)]: Cluster Node [akka.tcp://KillrWeather@127.0.0.1:2550] - Started up successfully
[INFO] [2015-12-15 16:40:53,523] [Cluster(akka://KillrWeather)]: Cluster Node [akka.tcp://KillrWeather@127.0.0.1:2550] - No seed-nodes configured, manual cluster join required
[INFO] [2015-12-15 16:40:53,652] [Cluster(akka://KillrWeather)]: Cluster Node [akka.tcp://KillrWeather@127.0.0.1:2550] - Metrics collection has started successfully
[error] (run-main-0) java.net.BindException: Cannot assign requested address
java.net.BindException: Cannot assign requested address
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Net.java:433)
        at sun.nio.ch.Net.bind(Net.java:425)
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
        at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
        at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:67)
        at org.apache.zookeeper.server.NIOServerCnxnFactory.configure(NIOServerCnxnFactory.java:95)
        at com.datastax.spark.connector.embedded.EmbeddedZookeeper.<init>(EmbeddedZookeeper.scala:51)
        at com.datastax.spark.connector.embedded.EmbeddedKafka.<init>(EmbeddedKafka.scala:23)
        at com.datastax.spark.connector.embedded.EmbeddedKafka.<init>(EmbeddedKafka.scala:15)
        at com.datastax.spark.connector.embedded.EmbeddedKafka.<init>(EmbeddedKafka.scala:20)
        at com.datastax.killrweather.KillrWeather.<init>(KillrWeatherApp.scala:77)
        at com.datastax.killrweather.KillrWeather$.createExtension(KillrWeatherApp.scala:54)
        at com.datastax.killrweather.KillrWeather$.createExtension(KillrWeatherApp.scala:50)
        at akka.actor.ActorSystemImpl.registerExtension(ActorSystem.scala:713)
        at akka.actor.ExtensionId$class.apply(Extension.scala:79)
        at com.datastax.killrweather.KillrWeather$.apply(KillrWeatherApp.scala:50)
        at com.datastax.killrweather.KillrWeatherApp$delayedInit$body.apply(KillrWeatherApp.scala:46)
        at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
        at scala.App$$anonfun$main$1.apply(App.scala:71)
        at scala.App$$anonfun$main$1.apply(App.scala:71)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:32)
        at scala.App$class.main(App.scala:71)
        at com.datastax.killrweather.KillrWeatherApp$.main(KillrWeatherApp.scala:38)
        at com.datastax.killrweather.KillrWeatherApp.main(KillrWeatherApp.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
[trace] Stack trace suppressed: run last app/*:run for the full output.
^C^Croot@load1:~/git/killrweather# ^C

**Comment by ksully2** [comment]
i got the same issue. Helena, any clue would be appreciated

**Comment by yoseldvp** [comment]
Since you are running this as a root user it's not related to permisions. It might be something related to your hosts file configuration. Can you paste your /etc/hosts file here?

**Comment by helena** [comment]
@ksully2 @dipietro-salvatore this is just a problem on your system from trying to connect to the default host:port for zookeeper: 

host: InetAddress.getLocalHost.getHostAddress
port: 2181
