### ISSUE TITLE
start from a new Cassandra

### ISSUE THREAD

**Issue by carreymu** [killrweather/killrweather#31]
I try to run the examples.
first, I got the newest Cassandra 3.0.3, and I got this Error:
`16/03/02 11:29:57 ERROR NIOServerCnxnFactory: Thread Thread[main,5,main] died
java.io.IOException: Failed to open native connection to Cassandra at {192.168.211.128}:9042
	at com.datastax.spark.connector.cql.CassandraConnector$.com$datastax$spark$connector$cql$CassandraConnector$$createSession(CassandraConnector.scala:181)
	at com.datastax.spark.connector.cql.CassandraConnector$$anonfun$2.apply(CassandraConnector.scala:167)
	at com.datastax.spark.connector.cql.CassandraConnector$$anonfun$2.apply(CassandraConnector.scala:167)
	at com.datastax.spark.connector.cql.RefCountedCache.createNewValueAndKeys(RefCountedCache.scala:31)
	at com.datastax.spark.connector.cql.RefCountedCache.acquire(RefCountedCache.scala:56)
	at com.datastax.spark.connector.cql.CassandraConnector.openSession(CassandraConnector.scala:76)
	at com.datastax.spark.connector.cql.CassandraConnector.withSessionDo(CassandraConnector.scala:104)`

then I got the Cassandra 2.1, it works.
Actually we use Cassandra 3.0.x in the test environment, how can I do to fix this? 
What if I upgrate the other dependencies?
I'm new to spark, tell me step by step please.
Many thanks.

**Comment by helena** [comment]
Hi @carreymu, please see the version of cassandra this was last built against (which was a long time ago now) https://github.com/killrweather/killrweather/blob/master/project/Versions.scala#L23 So yes, if you are using a newer version you will get that error ;) If you would like to contribute a PR for the upgrade (with cassandra, the driver and the spark cassandra connector) that is consistent with all binaries and passes IT tests and the runtime demos and samples, that would be greatly appreciated!

**Comment by laugimethods** [comment]
Hi @carreymu, even with the latest librairies version I wasn't able to make it work with Cassandra 3.0.3... :-(

See [FutureT: @uncheckedVariance #30](https://github.com/killrweather/killrweather/pull/30)
