### ISSUE TITLE
ERROR SparkDeploySchedulerBackend: Application has been killed. Reason: All masters are unresponsive! Giving up

### ISSUE THREAD

**Issue by carreymu** [killrweather/killrweather#32]
I try to run [SimpleSparkJob].
It works well if I do not change anything.
I want to run the Demo to a Cluster,and change the code like this:
`  val conf = new SparkConf(true).set("spark.cassandra.connection.host", "127.0.0.1")
      .**setMaster("spark://192.168.210.47:7077").**setAppName("spark.cassandra.connection")`
The IDE return this error:
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
16/03/03 15:29:46 INFO SparkContext: Running Spark version 1.3.1
16/03/03 15:29:46 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
16/03/03 15:29:47 INFO SecurityManager: Changing view acls to: root
16/03/03 15:29:47 INFO SecurityManager: Changing modify acls to: root
16/03/03 15:29:47 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: Set(root); users with modify permissions: Set(root)
16/03/03 15:29:47 INFO Slf4jLogger: Slf4jLogger started
16/03/03 15:29:47 INFO Remoting: Starting remoting
16/03/03 15:29:47 INFO Remoting: Remoting started; listening on addresses :[akka.tcp://sparkDriver@Master:44565]
16/03/03 15:29:47 INFO Utils: Successfully started service 'sparkDriver' on port 44565.
16/03/03 15:29:47 INFO SparkEnv: Registering MapOutputTracker
16/03/03 15:29:47 INFO SparkEnv: Registering BlockManagerMaster
16/03/03 15:29:47 INFO DiskBlockManager: Created local directory at /tmp/spark-d7c6da22-eed7-469f-a120-f3aa0fb6d650/blockmgr-6bed18a9-6b12-4963-baae-ab99c60efadc
16/03/03 15:29:47 INFO MemoryStore: MemoryStore started with capacity 958.2 MB
16/03/03 15:29:47 INFO HttpFileServer: HTTP File server directory is /tmp/spark-81b29c62-e8a7-48a3-99f1-15789561cc16/httpd-b4767476-467f-41be-90d4-051a7a5d8171
16/03/03 15:29:47 INFO HttpServer: Starting HTTP Server
16/03/03 15:29:47 INFO Server: jetty-8.y.z-SNAPSHOT
16/03/03 15:29:47 INFO AbstractConnector: Started SocketConnector@0.0.0.0:58063
16/03/03 15:29:47 INFO Utils: Successfully started service 'HTTP file server' on port 58063.
16/03/03 15:29:48 INFO SparkEnv: Registering OutputCommitCoordinator
16/03/03 15:29:53 INFO Server: jetty-8.y.z-SNAPSHOT
16/03/03 15:29:53 INFO AbstractConnector: Started SelectChannelConnector@0.0.0.0:4040
16/03/03 15:29:53 INFO Utils: Successfully started service 'SparkUI' on port 4040.
16/03/03 15:29:53 INFO SparkUI: Started SparkUI at http://Master:4040
16/03/03 15:29:53 INFO AppClient$ClientActor: Connecting to master akka.tcp://sparkMaster@192.168.210.47:7077/user/Master...
16/03/03 15:30:13 INFO AppClient$ClientActor: Connecting to master akka.tcp://sparkMaster@192.168.210.47:7077/user/Master...
16/03/03 15:30:33 INFO AppClient$ClientActor: Connecting to master akka.tcp://sparkMaster@192.168.210.47:7077/user/Master...
16/03/03 15:30:53 ERROR SparkDeploySchedulerBackend: Application has been killed. Reason: All masters are unresponsive! Giving up.
16/03/03 15:30:53 WARN SparkDeploySchedulerBackend: Application ID is not initialized yet.
16/03/03 15:30:53 ERROR TaskSchedulerImpl: Exiting due to error from cluster scheduler: All masters are unresponsive! Giving up.
---------
It seems that something wrong with akka.tcp://sparkMaster@192.168.210.47:7077/user/Master,
so I run this code:
`object RemoteActorApp extends App {
  val system = ActorSystem("spike-spark-issue")
  val actor = system.actorSelection("akka.tcp://sparkMaster@192.168.210.47:7077/user/Master")
  if (actor == null) println("null actor") else println("correct")
}`
that returns **correct**.
Any good advice? 
Many thx.

**Comment by laugimethods** [comment]
I don't know if it will solve your own issue, but I wan't able to connect the client to the app while the firewall (on OS X) was set to on.
I solved that issue by specifying the [local]host, so that the computer's IP is not used:
`sbt app/run -Dcassandra.connection.host="localhost"`

**Comment by carreymu** [comment]
@laugimethods thank you for your advice. I'm very sure I can connect the cluster, and it is running well. I run the spark example [Broadcast Test]  (folder path: spark-1.6.0-bin-hadoop2.6/examples/src/main/scala/org/apache/spark/examples) and  [http://192.168.210.47:8080/ ] shows what job I have submitted.
Follow the path  [Completed Applications]->[Executor Summary] on the page [http://192.168.210.47:8080/] I find some execute logs,each of their State is [EXITED],  I click the  [stderr] , it says:
`16/03/03 08:14:41 INFO CoarseGrainedExecutorBackend: Registered signal handlers for [TERM, HUP, INT]
16/03/03 08:14:41 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
16/03/03 08:14:41 INFO SecurityManager: Changing view acls to: root
16/03/03 08:14:41 INFO SecurityManager: Changing modify acls to: root
16/03/03 08:14:41 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: Set(root); users with modify permissions: Set(root)
Exception in thread "main" java.io.IOException: Failed to connect to /192.168.220.38:41806
	at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:216)
	at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:167)
	at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:200)
	at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:187)
	at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:183)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection timed out: /192.168.220.38:41806
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:224)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:289)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:528)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
	... 1 more`


[192.168.220.38] is my Virtual computer's ip, maybe something is wrong in config file.
----------------------
If  I run [KillrWeather] to a  spark cluster and cassandra is running in another cluster, what config file  should I change?
