### ISSUE TITLE
Exception thrown when sample no longer has any un-queried data

### ISSUE THREAD

**Issue by searler** [killrweather/killrweather#4]
```
[ERROR] [2015-01-30 21:04:58,616] [akka.actor.OneForOneStrategy]: next on empty iterator
java.util.NoSuchElementException: next on empty iterator
        at scala.collection.Iterator$$anon$2.next(Iterator.scala:39) ~[scala-library.jar:0.13.5]
        at scala.collection.Iterator$$anon$2.next(Iterator.scala:37) ~[scala-library.jar:0.13.5]
        at scala.collection.IterableLike$class.head(IterableLike.scala:91) ~[scala-library.jar:0.13.5]
        at scala.collection.AbstractIterable.head(Iterable.scala:54) ~[scala-library.jar:0.13.5]
        at com.datastax.killrweather.WeatherApiQueries.queries(KillrWeatherClientApp.scala:77) ~[classes/:na]
        at com.datastax.killrweather.WeatherApiQueries$$anonfun$receive$1.applyOrElse(KillrWeatherClientApp.scala:61) ~[classes/:na]
        at akka.actor.Actor$class.aroundReceive(Actor.scala:465) ~[akka-actor_2.10-2.3.8.jar:na]
        at com.datastax.killrweather.WeatherApiQueries.aroundReceive(KillrWeatherClientApp.scala:37) ~[classes/:na]
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516) [akka-actor_2.10-2.3.8.jar:na]
        at akka.actor.ActorCell.invoke(ActorCell.scala:487) [akka-actor_2.10-2.3.8.jar:na]
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:254) [akka-actor_2.10-2.3.8.jar:na]
        at akka.dispatch.Mailbox.run(Mailbox.scala:221) [akka-actor_2.10-2.3.8.jar:na]
        at akka.dispatch.Mailbox.exec(Mailbox.scala:231) [akka-actor_2.10-2.3.8.jar:na]
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library.jar:na]
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library.jar:na]
```

Which is generated from
```
val sample: Day = fileFeed().flatMap { case f =>
      val source = FileSource(f).source
      val s = source.getLines().map(Day(_)).filterNot(previous).toSeq.headOption
      Try(source.close())
      s
    }.head
```

The final ```head``` will fail if all the data has been previously queried.

**Comment by searler** [comment]
There are only 5 unique wsids in the dataset
```
Set(724940, 722020, 725300, 725030, 722950)
```

So the query client starts throwing exceptions after 5 queries have been executed.

**Comment by helena** [comment]
fixed.
